apiVersion: v1
kind: Service
metadata:
  name: {{ include "plugin-br-payments-fakebtg.fullname" . }}
  namespace: {{ include "global.namespace" . }}
  labels:
    {{- include "plugin-br-payments-fakebtg.labels" (dict "context" .) | nindent 4 }}
  {{- with .Values.fakebtg.service.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.fakebtg.service.type }}
  ports:
    - port: {{ .Values.fakebtg.service.port }}
      targetPort: {{ .Values.fakebtg.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "plugin-br-payments-fakebtg.selectorLabels" (dict "context" .) | nindent 4 }}
