{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "plugin-frontend.fullname" . }}
  labels:
    {{- include "plugin-frontend.labels" (dict "context" . "name" .Values.frontend.name ) | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "plugin-frontend.selectorLabels" (dict "context" . "name" .Values.frontend.name) | nindent 4 }}
{{- end }}