{{- if and .Values.adapterBtgMock.enabled .Values.adapterBtgMock.serviceAccount.create }}
{{- $component := "adapter-btg-mock" }}
{{- $values := .Values.adapterBtgMock }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "plugin-br-pix-switch.componentServiceAccountName" (dict "context" $ "component" $component "componentValues" $values) }}
  labels:
    {{- include "plugin-br-pix-switch.labels" (dict "context" $ "component" $component) | nindent 4 }}
  {{- with $values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
