{{- if .Values.api.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "br-consignado-gw.apiFullname" . }}
  namespace: {{ include "br-consignado-gw.namespace" . }}
  labels:
    {{- include "br-consignado-gw.componentLabels" (dict "root" . "name" "api") | nindent 4 }}
data:
  {{- range $key, $value := .Values.api.configmap }}
  {{ $key }}: {{ $value | toString | quote }}
  {{- end }}
  VERSION: {{ .Values.api.image.tag | default .Chart.AppVersion | quote }}
{{- end }}
