apiVersion: v1
kind: Secret
metadata:
  name: {{ include "plugin-br-pix-direct-jd.fullname" . }}
  labels:
    {{- include "plugin-br-pix-direct-jd.labels" (dict "context" . "name" .Values.pix.name ) | nindent 4 }}
type: Opaque
data:
  # -- Default sensitive variables for the plugin-br-pix-direct-jd
  # License Configuration
  LICENSE_KEY: {{ .Values.pix.secrets.LICENSE_KEY | default "" | b64enc | quote }}

  # Midaz Configuration
  MIDAZ_CLIENT_ID: {{ .Values.pix.secrets.MIDAZ_CLIENT_ID | default "" | b64enc | quote }}
  MIDAZ_CLIENT_SECRET: {{ required "pix.secrets.MIDAZ_CLIENT_SECRET is required" .Values.pix.secrets.MIDAZ_CLIENT_SECRET | b64enc | quote }}

  # CRM Configuration
  CRM_CLIENT_ID: {{ .Values.pix.secrets.CRM_CLIENT_ID | default "" | b64enc | quote }}
  CRM_CLIENT_SECRET: {{ .Values.pix.secrets.CRM_CLIENT_SECRET | default "" | b64enc | quote }}

  # JD Pix Configuration
  JD_CLIENT_ID: {{ .Values.pix.secrets.JD_CLIENT_ID | default "" | b64enc | quote }}
  JD_SECRET: {{ required "pix.secrets.JD_SECRET is required" .Values.pix.secrets.JD_SECRET | b64enc | quote }}
  JD_PIX_CLIENT_ID: {{ .Values.pix.secrets.JD_PIX_CLIENT_ID | default "" | b64enc | quote }}
  JD_PIX_CLIENT_SECRET: {{ required "pix.secrets.JD_PIX_CLIENT_SECRET is required" .Values.pix.secrets.JD_PIX_CLIENT_SECRET | b64enc | quote }}

  # Postgres Service 
  DATABASE_PASSWORD: {{ required "pix.secrets.DATABASE_PASSWORD is required" .Values.pix.secrets.DATABASE_PASSWORD | b64enc | quote }}
  POSTGRES_PASSWORD: {{ required "pix.secrets.POSTGRES_PASSWORD is required" .Values.pix.secrets.POSTGRES_PASSWORD | b64enc | quote }}

  # Twilio Configuration
  TWILIO_AUTH_TOKEN: {{ .Values.pix.secrets.TWILIO_AUTH_TOKEN | default "" | b64enc | quote }}
  TWILIO_ACCOUNT_SID: {{ .Values.pix.secrets.TWILIO_ACCOUNT_SID | default "" | b64enc | quote }}

  # SendGrid Configuration
  SENDGRID_API_KEY: {{ .Values.pix.secrets.SENDGRID_API_KEY | default "" | b64enc | quote }}

  SECRET_KEY_BASE: {{ required "pix.secrets.SECRET_KEY_BASE is required" .Values.pix.secrets.SECRET_KEY_BASE | b64enc | quote }}
