{{- if .Values.app.enabled -}}
{{- include "br-spi-mock-bacen.validateEnvironment" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "br-spi-mock-bacen.fullname" . }}
  namespace: {{ include "global.namespace" . }}
  labels:
    {{- include "br-spi-mock-bacen.labels" . | nindent 4 }}
  {{- with (.Values.global | default dict).commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- include "br-spi-mock-bacen.configmapData" . | nindent 2 }}
{{- end }}
