{{- if .Values.app.enabled -}}
{{- include "br-spi-mock-bacen.validateEnvironment" . -}}
{{- include "br-spi-mock-bacen.validateService" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "br-spi-mock-bacen.fullname" . }}
  namespace: {{ include "global.namespace" . }}
  labels:
    {{- include "br-spi-mock-bacen.labels" . | nindent 4 }}
  {{- $annotations := merge (dict) (.Values.app.service.annotations | default dict) ((.Values.global | default dict).commonAnnotations | default dict) }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - name: http
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "br-spi-mock-bacen.selectorLabels" . | nindent 4 }}
{{- end }}
