apiVersion: v1
kind: Secret
metadata:
  name: {{ include "midaz-helm.fullname" . }}-tracer
  labels:
    {{- include "midaz-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: tracer
type: Opaque
data:
  API_KEY: {{ .Values.tracer.secrets.API_KEY | default "dev_api_key_32chars_change_in_prod" | b64enc | quote }}
  API_KEY_ENABLED: {{ .Values.tracer.secrets.API_KEY_ENABLED | default "false" | b64enc | quote }}
  API_KEY_ENABLED_ONLY_VALIDATION: {{ .Values.tracer.secrets.API_KEY_ENABLED_ONLY_VALIDATION | default "false" | b64enc | quote }}
  API_KEY_LABEL: {{ .Values.tracer.secrets.API_KEY_LABEL | default "tracer-default" | b64enc | quote }}
  DB_PASSWORD: {{ .Values.tracer.secrets.DB_PASSWORD | default "lerian" | b64enc | quote }}
  IDP_M2M_CLIENT_SECRET: {{ .Values.tracer.secrets.IDP_M2M_CLIENT_SECRET | default "" | b64enc | quote }}
  MULTI_TENANT_REDIS_PASSWORD: {{ .Values.tracer.secrets.MULTI_TENANT_REDIS_PASSWORD | default "" | b64enc | quote }}
  MULTI_TENANT_SERVICE_API_KEY: {{ .Values.tracer.secrets.MULTI_TENANT_SERVICE_API_KEY | default "" | b64enc | quote }}
  SD_TOKEN: {{ .Values.tracer.secrets.SD_TOKEN | default "" | b64enc | quote }}
  # Extra Secret Vars
  {{- if .Values.tracer.extraSecretVars }}
  {{- toYaml .Values.tracer.extraSecretVars | nindent 2 }}
  {{- end }}
