apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "plugin-manager.fullname" . }}
  labels:
    {{- include "plugin-manager.labels" (dict "context" . "name" .Values.manager.name ) | nindent 4 }}
  {{- with .Values.manager.configmap.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }} 
data:
  # Common shared values
  {{- range $key, $value := .Values.common.configmap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  # Service specific values
  {{- range $key, $value := .Values.manager.configmap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}