apiVersion: v1
kind: Secret
metadata:
  name: {{ include "streaming-hub-helm.fullname" . }}-streaming-hub
  labels:
    {{- include "streaming-hub-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: streaming-hub
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.streaming-hub.secrets.POSTGRES_PASSWORD | default "streaming_hub" | b64enc | quote }}
  # Extra Secret Vars
  {{- if .Values.streaming-hub.extraSecretVars }}
  {{- toYaml .Values.streaming-hub.extraSecretVars | nindent 2 }}
  {{- end }}
