apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "plugin-br-pix-direct-jd-qr-code.fullname" . }}
  labels:
    {{- include "plugin-br-pix-direct-jd-qr-code.labels" (dict "context" . "name" .Values.qrcode.name ) | nindent 4 }}
data:
  # APP
  VERSION: {{ .Values.qrcode.image.tag | default .Chart.AppVersion | quote }}
  SERVER_PORT: "4009"
  SERVER_ADDRESS: ":4009"
  LOG_LEVEL: {{ .Values.qrcode.configmap.LOG_LEVEL | default "info" | quote }}

  # -- Default Environment variables for the cert-provider