{{- if not .Values.qrcode.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "plugin-br-pix-direct-jd-qr-code.fullname" . }}
  labels:
    {{- include "plugin-br-pix-direct-jd-qr-code.labels" (dict "context" . "name" .Values.qrcode.name ) | nindent 4 }} 
type: Opaque
data:
  # -- Default sensitive variables for the cert-provider
  # MONGO Secrets
  PRIVATE_KEY: {{ .Values.qrcode.secrets.PRIVATE_KEY | default "" | b64enc | quote }}
  CERTIFICATE: {{ .Values.qrcode.secrets.CERTIFICATE | default "lerian" | b64enc | quote }}
{{- end }}