{{- if .Values.streamingHub.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "streaming-hub.serviceAccountName" . }}
  namespace: {{ include "global.namespace" . }}
  labels:
    {{- include "streaming-hub.labels" (dict "context" . "component" "all") | nindent 4 }}
  {{- with .Values.streamingHub.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
