{{- if .Values.streamingHub.serviceAccount.create }}
{{- include "lerian-common.serviceAccount" (dict
      "serviceAccount" .Values.streamingHub.serviceAccount
      "name" (include "streaming-hub.serviceAccountName" .)
      "namespace" (include "global.namespace" .)
      "labels" (include "streaming-hub.labels" (dict "context" . "component" "all"))
    ) }}
{{- end }}
