{{- if eq (include "flowker.worker.enabled" .) "true" }}
{{- $w := .Values.worker | default dict -}}
{{- $sa := $w.serviceAccount | default dict -}}
{{- if $sa.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flowker.worker.serviceAccountName" . }}
  namespace: {{ include "global.namespace" . }}
  labels:
    {{- include "flowker.worker.labels" (dict "context" .) | nindent 4 }}
  {{- with $sa.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
