apiVersion: v1
kind: Secret
metadata:
  name: plugin-smart-templates-minio-users
  labels:
    {{- include "plugin-worker.labels" (dict "context" . "name" .Values.worker.name ) | nindent 4 }}   
type: Opaque
stringData:
  plugin: |
    username=lerian
    password=Lerian@123
    disabled=false
    policies=readwrite
    setPolicies=true