apiVersion: v1
kind: Secret
metadata:
  name: {{ include "plugin-worker.fullname" . }}
  labels:
    {{- include "plugin-worker.labels" (dict "context" . "name" .Values.worker.name ) | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"
type: Opaque
data:
  MONGO_PASSWORD: {{ .Values.secrets.MONGO_PASSWORD | default "lerian" | b64enc | quote }}
  MINIO_APP_PASSWORD_WORKER: {{ .Values.secrets.MINIO_APP_PASSWORD_WORKER | default "LerianWorker@123" | b64enc | quote }}
  MINIO_APP_PASSWORD_MANAGER: {{ .Values.secrets.MINIO_APP_PASSWORD_MANAGER | default "LerianManager@123" | b64enc | quote }}
  RABBITMQ_DEFAULT_USER: {{ .Values.secrets.RABBITMQ_DEFAULT_USER | default "plugin" | b64enc | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.secrets.RABBITMQ_DEFAULT_PASS | default "Lerian@123" | b64enc | quote }}
  DATASOURCE_FEES_PASSWORD: {{ .Values.secrets.DATASOURCE_FEES_PASSWORD | default "plugin-fees" | b64enc | quote }}
  DATASOURCE_TRANSACTION_METADATA_PASSWORD: {{ .Values.secrets.DATASOURCE_TRANSACTION_METADATA_PASSWORD | default "plugin" | b64enc | quote }}
  DATASOURCE_ONBOARDING_METADATA_PASSWORD: {{ .Values.secrets.DATASOURCE_ONBOARDING_METADATA_PASSWORD | default "plugin" | b64enc | quote }}
  DATASOURCE_TRANSACTION_PASSWORD: {{ .Values.secrets.DATASOURCE_TRANSACTION_PASSWORD | default "plugin" | b64enc | quote }}
  DATASOURCE_ONBOARDING_PASSWORD: {{ .Values.secrets.DATASOURCE_ONBOARDING_PASSWORD | default "plugin" | b64enc | quote }}