apiVersion: v1
kind: Service
metadata:
  name: {{ include "plugin-worker.fullname" . }}
  labels:
    {{- include "plugin-worker.labels" (dict "context" . "name" .Values.worker.name ) | nindent 4 }}
  {{- with .Values.worker.service.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }} 
spec:
  type: {{ .Values.worker.service.type }}
  ports:
    - port: {{ .Values.worker.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "plugin-worker.selectorLabels" (dict "context" . "name" .Values.worker.name) | nindent 4 }}