{{- if and .Values.boilerplate.enabled .Values.boilerplate.pdb.enabled }}
{{- if and .Values.boilerplate.pdb.minAvailable .Values.boilerplate.pdb.maxUnavailable }}
  {{- fail "pdb: set either minAvailable or maxUnavailable, not both" }}
{{- end }}
{{- if and (not .Values.boilerplate.pdb.minAvailable) (not .Values.boilerplate.pdb.maxUnavailable) }}
  {{- fail "pdb: at least one of minAvailable or maxUnavailable must be set" }}
{{- end }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "boilerplate.fullname" . }}
  namespace: {{ include "global.namespace" . }}
  labels:
    {{- include "boilerplate.labels" (dict "context" . "component" .Values.boilerplate.name "name" .Values.boilerplate.name) | nindent 4 }}
  {{- with .Values.boilerplate.pdb.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.boilerplate.pdb.minAvailable }}
  minAvailable: {{ .Values.boilerplate.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.boilerplate.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.boilerplate.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "boilerplate.selectorLabels" (dict "context" . "name" .Values.boilerplate.name) | nindent 6 }}
{{- end }}
