{{- if and .Values.boilerplate.enabled (not .Values.boilerplate.useExistingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "boilerplate.fullname" . }}
  namespace: {{ include "global.namespace" . }}
  labels:
    {{- include "boilerplate.labels" (dict "context" . "component" .Values.boilerplate.name "name" .Values.boilerplate.name) | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.boilerplate.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
