{{- if .Values.autoscaling.enabled }}
{{- include "lerian-common.hpa" (dict
      "autoscaling" .Values.autoscaling
      "name" (include "product-console.fullname" .)
      "labels" (include "product-console.labels" .)
    ) }}
{{- end }}
