{{- if .Values.pdb.enabled }}
{{- include "lerian-common.pdb" (dict
      "pdb" .Values.pdb
      "name" (include "product-console.fullname" .)
      "labels" (include "product-console.labels" .)
      "selector" (include "product-console.selectorLabels" .)
      "minAvailableDefault" 1
    ) }}
{{- end }}
