{{- if and .Values.spiSystemplane.enabled (not .Values.spiSystemplane.useExistingSecret) }}
{{- $component := "spi-systemplane" }}
{{- $values := .Values.spiSystemplane }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "plugin-br-pix-switch.componentFullname" (dict "context" $ "component" $component) }}
  namespace: {{ include "global.namespace" . }}
  labels:
    {{- include "plugin-br-pix-switch.labels" (dict "context" $ "component" $component) | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := $values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
