apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plugin-crm.fullname" . }}
  labels:
    {{- include "plugin-crm.labels" (dict "context" . "name" .Values.name ) | nindent 4 }} 
spec:
  strategy:
    {{- toYaml .Values.deploymentStrategy | nindent 4 }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "plugin-crm.selectorLabels" (dict "context" . "name" .Values.name) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "plugin-crm.labels" (dict "context" . "name" .Values.name ) | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "plugin-crm.fullname" . }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default (include "plugin.version" .) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          envFrom:
          - secretRef:
              name: {{ include "plugin-crm.fullname" . }}
          - configMapRef:
              name: {{ include "plugin-crm.fullname" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /health
              port: {{ .Values.service.port }}   
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}