apiVersion: v1
kind: Service
metadata:
  name: {{ include "plugin-crm.fullname" . }}
  labels:
    {{- include "plugin-crm.labels" (dict "context" . "name" .Values.name ) | nindent 4 }} 
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "plugin-crm.selectorLabels" (dict "context" . "name" .Values.name) | nindent 4 }}