apiVersion: v1
kind: Secret
metadata:
  name: {{ include "plugin-crm.fullname" . }}
  labels:
    {{- include "plugin-crm.labels" (dict "context" . "name" .Values.crm.name ) | nindent 4 }}
type: Opaque
data:
  # -- Default sensitive variables for the plugin-crm

  # DATA SECURITY
  LCRYPTO_HASH_SECRET_KEY: {{ .Values.crm.secrets.LCRYPTO_HASH_SECRET_KEY | default "my-hash-secret-key" | b64enc | quote }}
  LCRYPTO_ENCRYPT_SECRET_KEY: {{ .Values.crm.secrets.LCRYPTO_ENCRYPT_SECRET_KEY | default "my-encrypt-secret-key" | b64enc | quote }}
  # MONGO Secrets
  MONGO_PASSWORD: {{ .Values.crm.secrets.MONGO_PASSWORD | default "lerian" | b64enc| quote }}
  # LICENSE Secrets
  LICENSE_KEY: {{ .Values.crm.secrets.LICENSE_KEY | b64enc | quote }}
  ORGANIZATION_IDS: {{ .Values.crm.secrets.ORGANIZATION_IDS | b64enc | quote }}
