{{- if .Values.caradhras.ui.enabled }}
{{- $ui := .Values.caradhras.ui -}}
{{- $uiSvc := $ui.service | default dict -}}
{{- include "lerian-common.service" (dict
      "service" (dict "type" ($uiSvc.type | default "ClusterIP") "port" ($uiSvc.port | default 80) "annotations" $uiSvc.annotations)
      "name" (include "plugin-caradhras-ui.fullname" .)
      "labels" (printf "%s " (include "plugin-caradhras-ui.labels" (dict "context" . "name" $ui.name)))
      "selector" (include "plugin-caradhras-ui.selectorLabels" (dict "context" . "name" $ui.name))
    ) }}
{{- end }}
