{{- if .Values.fees.autoscaling.enabled }}
{{- include "lerian-common.hpa" (dict
      "autoscaling" .Values.fees.autoscaling
      "name" (include "plugin-fees.fullname" .)
      "labels" (include "plugin-fees.labels" (dict "context" . "name" .Values.fees.name))
    ) }}
{{- end }}
