{{- if .Values.fees.ingress.enabled -}}
{{- include "lerian-common.ingress" (dict
      "context" .
      "ingress" .Values.fees.ingress
      "name" (include "plugin-fees.fullname" .)
      "labels" (include "plugin-fees.labels" (dict "context" . "name" .Values.fees.name))
      "svcPort" .Values.fees.service.port
    ) }}
{{- end }}
