{{- include "lerian-common.service" (dict
      "service" .Values.fees.service
      "name" (include "plugin-fees.fullname" .)
      "labels" (include "plugin-fees.labels" (dict "context" . "name" .Values.fees.name))
      "selector" (include "plugin-fees.selectorLabels" (dict "context" . "name" .Values.fees.name))
    ) }}
