{{- if .Values.fees.serviceAccount.create -}}
{{- include "lerian-common.serviceAccount" (dict
      "serviceAccount" .Values.fees.serviceAccount
      "name" (include "plugin-fees.fullname" .)
      "labels" (include "plugin-fees.labels" (dict "context" . "name" .Values.fees.name))
    ) }}
{{- end }}
