{{- if $.Values.correios.enabled -}}
{{ include "br-sfn.correiosConfigmap" (dict "root" $ "name" "correios" "comp" $.Values.correios "port" ($.Values.correios.service.port | default 8080)) }}
{{- end -}}
