{{- if .Values.ledger.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "midaz-ledger.fullname" . }}
  labels:
    {{- include "midaz.labels" (dict "context" . "component" .Values.ledger.name "name" .Values.ledger.name ) | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "midaz-ledger.fullname" . }}
  minReplicas: {{ .Values.ledger.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.ledger.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.ledger.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.ledger.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.ledger.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.ledger.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
