{{- $gIng := (.Values.global | default dict).ingress | default dict -}}
{{- if and .Values.ledger.enabled (or .Values.ledger.ingress.enabled $gIng.enabled) -}}
{{- include "lerian-common.ingress" (dict
      "context" .
      "ingress" .Values.ledger.ingress
      "global" $gIng
      "subdomain" "ledger"
      "name" (include "midaz-ledger.fullname" .)
      "labels" (include "midaz.labels" (dict "context" . "component" .Values.ledger.name "name" .Values.ledger.name))
      "svcPort" .Values.ledger.service.port
    ) }}
{{- end }}
