apiVersion: v1
kind: Secret
metadata:
  name: {{ include "midaz-helm.fullname" . }}-ledger
  labels:
    {{- include "midaz-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: ledger
type: Opaque
data:
  TRACER_API_KEY: {{ .Values.ledger.secrets.TRACER_API_KEY | default "" | b64enc | quote }}
  TRACER_M2M_CLIENT_SECRET: {{ .Values.ledger.secrets.TRACER_M2M_CLIENT_SECRET | default "" | b64enc | quote }}
  # Extra Secret Vars
  {{- if .Values.ledger.extraSecretVars }}
  {{- toYaml .Values.ledger.extraSecretVars | nindent 2 }}
  {{- end }}
