{{- if and .Values.dictHub.enabled .Values.dictHub.pdb.enabled }}
{{- $component := "dict-hub" }}
{{- $values := .Values.dictHub }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "plugin-br-pix-switch.componentFullname" (dict "context" $ "component" $component) }}
  namespace: {{ include "global.namespace" . }}
  labels:
    {{- include "plugin-br-pix-switch.labels" (dict "context" $ "component" $component) | nindent 4 }}
  {{- with $values.pdb.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $values.pdb.minAvailable }}
  minAvailable: {{ $values.pdb.minAvailable }}
  {{- else if $values.pdb.maxUnavailable }}
  maxUnavailable: {{ $values.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "plugin-br-pix-switch.selectorLabels" (dict "context" $ "component" $component) | nindent 6 }}
{{- end }}
