{{- if .Values.worker.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "plugin-worker.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "plugin-worker.labels" (dict "context" . "name" .Values.worker.name ) | nindent 4 }}
  {{- $cloudAnn := include "lerian-common.cloud.saAnnotations" (dict "context" .) | trim }}
  {{- if or $cloudAnn .Values.worker.serviceAccount.annotations }}
  annotations:
    {{- with $cloudAnn }}{{ . | nindent 4 }}{{- end }}
    {{- with .Values.worker.serviceAccount.annotations }}{{- toYaml . | nindent 4 }}{{- end }}
  {{- end }}
{{- end }}
