apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "br-slc.fullname" . }}-signer
  labels:
    {{- include "br-slc.labels" . | nindent 4 }}
data:
  SIGNER_PKCS11_TOKEN_LABEL: {{ .Values.signer.pkcs11TokenLabel | quote }}
  {{- range $key, $value := .Values.signer.configmap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
