{{- if $.Values.scr.enabled -}}
{{ include "br-sfn.componentDeployment" (dict "root" $ "name" "scr" "comp" $.Values.scr "defaultPort" 3003 "livenessPath" "/health" "readyPath" "/readyz" "configDataOverride" (include "br-sfn.scrConfigData" (dict "root" $ "comp" $.Values.scr "port" ($.Values.scr.service.port | default 3003)))) }}
{{- end -}}
