{{- if and .Values.agent.enabled .Values.agent.serviceAccount.create }}
{{- include "lerian-common.serviceAccount" (dict
      "serviceAccount" .Values.agent.serviceAccount
      "name" (include "lerian-agent.serviceAccountName" .)
      "namespace" (include "global.namespace" .)
      "labels" (include "lerian-agent.labels" (dict "context" . "component" .Values.agent.name "name" .Values.agent.name))
    ) }}
{{- end }}
