apiVersion: v1
kind: Secret
metadata:
  name: {{ include "midaz-audit.fullname" . }}
type: Opaque
data:
  MONGO_PASSWORD: {{ .Values.ledger.configmap.MONGO_PASSWORD | default "lerian" | b64enc | quote }}
  DB_PASSWORD: {{ .Values.ledger.configmap.DB_PASSWORD | default "lerian" | b64enc | quote }}
  DB_REPLICA_PASSWORD: {{ .Values.ledger.configmap.DB_REPLICA_PASSWORD | default "lerian" | b64enc | quote }}
  REPLICATION_PASSWORD: {{ .Values.ledger.configmap.REPLICATION_PASSWORD | default "lerian" | b64enc | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.audit.configmap.RABBITMQ_DEFAULT_PASS | default "lerian" | b64enc | quote }}
  TRILLIAN_DATABASE_PASSWORD: {{ .Values.ledger.configmap.TRILLIAN_DATABASE_PASSWORD | default "lerian" | b64enc | quote }} 
  TRILLIAN_DATABASE_ROOT_PASSWORD: {{ .Values.ledger.configmap.TRILLIAN_DATABASE_ROOT_PASSWORD | default "lerian" | b64enc | quote }}