# Nenhuma verificação de API aqui
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "plugin-manager.fullname" . }}
  labels:
    {{- include "plugin-manager.labels" (dict "context" . "name" .Values.manager.name ) | nindent 4 }}
    {{- with .Values.manager.keda.scaledObject.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    "helm.sh/resource-policy": keep
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "5"
    {{- with .Values.manager.annotations }}
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "plugin-manager.fullname" . }}
  minReplicaCount: {{ .Values.manager.keda.scaledObject.minReplicaCount }}
  maxReplicaCount: {{ .Values.manager.keda.scaledObject.maxReplicaCount }}
  pollingInterval: {{ .Values.manager.keda.scaledObject.pollingInterval }}
  cooldownPeriod: {{ .Values.manager.keda.scaledObject.cooldownPeriod }}
  triggers:
  {{- range .Values.manager.keda.scaledObject.triggers }}
  - type: {{ .type }}
    metricType: {{ .metricType }}
    metadata:
      value: {{ .metadata.value | quote }}
      containerName: {{ .metadata.containerName }}
    authenticationRef:
      name: keda-trigger-authentication   
  {{- end }}