apiVersion: v1
kind: Secret
metadata:
  name: "reporter-manager-load-definitions"
type: Opaque
data:
  load_definition.json: |
    {{ .Files.Get "files/rabbitmq/load_definitions.json" | b64enc | nindent 4 }}