{{- if $.Values.spi.enabled -}}
{{ include "br-sfn.spiConfigmap" (dict "root" $ "name" "spi-api" "comp" $.Values.spi.api "port" ($.Values.spi.api.service.port | default 9800) "svcName" "pix-spi") }}
---
{{ include "br-sfn.spiConfigmap" (dict "root" $ "name" "spi-dict" "comp" $.Values.spi.dict "port" ($.Values.spi.dict.service.port | default 9801) "svcName" "pix-dict") }}
---
{{ include "br-sfn.spiConfigmap" (dict "root" $ "name" "spi-brcode" "comp" $.Values.spi.brcode "port" ($.Values.spi.brcode.service.port | default 9802) "svcName" "pix-brcode") }}
---
{{ include "br-sfn.spiConfigmap" (dict "root" $ "name" "spi-core" "comp" $.Values.spi.core "port" ($.Values.spi.core.service.port | default 9803) "svcName" "pix-core") }}
{{- end -}}
