{{- if $.Values.spi.enabled -}}
{{ include "br-sfn.componentSecrets" (dict "root" $ "name" "spi-api" "comp" $.Values.spi.api "shared" $.Values.spi.secrets "sharedCfg" $.Values.spi) }}
---
{{ include "br-sfn.componentSecrets" (dict "root" $ "name" "spi-dict" "comp" $.Values.spi.dict "shared" $.Values.spi.secrets "sharedCfg" $.Values.spi) }}
---
{{ include "br-sfn.componentSecrets" (dict "root" $ "name" "spi-brcode" "comp" $.Values.spi.brcode "shared" $.Values.spi.secrets "sharedCfg" $.Values.spi) }}
---
{{ include "br-sfn.componentSecrets" (dict "root" $ "name" "spi-core" "comp" $.Values.spi.core "shared" $.Values.spi.secrets "sharedCfg" $.Values.spi) }}
{{- end -}}
