apiVersion: v1
kind: Secret
metadata:
  name: {{ include "plugin-br-bank-transfer-helm.fullname" . }}-plugin-br-bank-transfer
  labels:
    {{- include "plugin-br-bank-transfer-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: plugin-br-bank-transfer
type: Opaque
data:
  CRM_CLIENT_SECRET: {{ .Values.bankTransfer.secrets.CRM_CLIENT_SECRET | default "" | b64enc | quote }}
  FEES_CLIENT_SECRET: {{ .Values.bankTransfer.secrets.FEES_CLIENT_SECRET | default "" | b64enc | quote }}
  JD_INCOMING_RAW_XML_ENCRYPTION_KEY: {{ .Values.bankTransfer.secrets.JD_INCOMING_RAW_XML_ENCRYPTION_KEY | default "" | b64enc | quote }}
  JD_PASSWORD: {{ .Values.bankTransfer.secrets.JD_PASSWORD | default "" | b64enc | quote }}
  LICENSE_KEY: {{ .Values.bankTransfer.secrets.LICENSE_KEY | default "" | b64enc | quote }}
  MIDAZ_CLIENT_SECRET: {{ .Values.bankTransfer.secrets.MIDAZ_CLIENT_SECRET | default "" | b64enc | quote }}
  MULTI_TENANT_REDIS_PASSWORD: {{ .Values.bankTransfer.secrets.MULTI_TENANT_REDIS_PASSWORD | default "" | b64enc | quote }}
  MULTI_TENANT_SERVICE_API_KEY: {{ .Values.bankTransfer.secrets.MULTI_TENANT_SERVICE_API_KEY | default "" | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.bankTransfer.secrets.POSTGRES_PASSWORD | default "" | b64enc | quote }}
  RECIPIENT_DETAILS_ENCRYPTION_KEY: {{ .Values.bankTransfer.secrets.RECIPIENT_DETAILS_ENCRYPTION_KEY | default "" | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.bankTransfer.secrets.REDIS_PASSWORD | default "" | b64enc | quote }}
  # Extra Secret Vars
  {{- if .Values.bankTransfer.extraSecretVars }}
  {{- toYaml .Values.bankTransfer.extraSecretVars | nindent 2 }}
  {{- end }}
