{{- if .Values.frontend.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "plugin-frontend.fullname" . }}
type: Opaque
data:
  NEXTAUTH_SECRET: {{ .Values.frontend.secrets.NEXTAUTH_SECRET | default "SECRET" | b64enc | quote }}
{{- end }}

