apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "schedule.fullname" . }}
  labels:
    {{- include "schedule.labels" (dict "context" . "name" .Values.schedule.name ) | nindent 4 }} 
spec:
  revisionHistoryLimit: {{ .Values.schedule.revisionHistoryLimit | default 10 }}
  strategy:
    {{- toYaml .Values.schedule.deploymentStrategy | nindent 4 }}
  replicas: {{ .Values.schedule.replicaCount }}
  selector:
    matchLabels:
      {{- include "schedule.selectorLabels" (dict "context" . "name" .Values.schedule.name) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "schedule.labels" (dict "context" . "name" .Values.schedule.name ) | nindent 8 }}
    spec:
    {{- with .Values.schedule.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.schedule.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "schedule.fullname" . }}
          securityContext:
            {{- toYaml .Values.schedule.securityContext | nindent 12 }}
          image: {{ .Values.schedule.image.repository }}:{{ .Values.schedule.image.tag | default (include "plugin.version" .) }}
          imagePullPolicy: {{ .Values.schedule.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.schedule.service.port }}
              protocol: TCP
          envFrom:
          - secretRef:
              name: {{ if .Values.schedule.useExistingSecrets }}{{ required "schedule.existingSecretName is required when schedule.useExistingSecrets is true" .Values.schedule.existingSecretName }}{{ else }}{{ include "schedule.fullname" . }}{{ end }}
          - configMapRef:
              name: {{ include "schedule.fullname" . }}
          {{- $otelEnabled := (index .Values "otel-collector-lerian").enabled }}
          {{- if $otelEnabled }}
          env:
          - name: "HOST_IP"
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: "OTEL_EXPORTER_OTLP_ENDPOINT"
            value: "$(HOST_IP):4317"
          {{- end }}
          resources:
            {{- toYaml .Values.schedule.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: {{ .Values.schedule.readinessProbe.path | default "/readyz" }}
              port: {{ .Values.schedule.service.port }}
            initialDelaySeconds: {{ .Values.schedule.readinessProbe.initialDelaySeconds | default 5 }}
            periodSeconds: {{ .Values.schedule.readinessProbe.periodSeconds | default 5 }}
            timeoutSeconds: {{ .Values.schedule.readinessProbe.timeoutSeconds | default 1 }}
            successThreshold: {{ .Values.schedule.readinessProbe.successThreshold | default 1 }}
            failureThreshold: {{ .Values.schedule.readinessProbe.failureThreshold | default 3 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.schedule.livenessProbe.path | default "/health" }}
              port: {{ .Values.schedule.service.port }}
            initialDelaySeconds: {{ .Values.schedule.livenessProbe.initialDelaySeconds | default 10 }}
            periodSeconds: {{ .Values.schedule.livenessProbe.periodSeconds | default 5 }}
            timeoutSeconds: {{ .Values.schedule.livenessProbe.timeoutSeconds | default 1 }}
            successThreshold: {{ .Values.schedule.livenessProbe.successThreshold | default 1 }}
            failureThreshold: {{ .Values.schedule.livenessProbe.failureThreshold | default 3 }}
      {{- with .Values.schedule.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.schedule.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.schedule.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
