{{- if and .Values.lender.enabled .Values.lender.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lender.serviceAccountName" . }}
  namespace: {{ include "global.namespace" . }}
  labels:
    {{- include "lender.labels" (dict "context" . "component" .Values.lender.name "name" .Values.lender.name) | nindent 4 }}
  {{- with .Values.lender.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
