apiVersion: v1
kind: Service
metadata:
  name: {{ include "plugin-identity.fullname" . }}
  labels:
    {{- include "plugin-identity.labels" (dict "context" . "name" .Values.identity.name ) | nindent 4 }} 
spec:
  type: {{ .Values.identity.service.type }}
  ports:
    - port: {{ .Values.identity.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "plugin-identity.selectorLabels" (dict "context" . "name" .Values.identity.name) | nindent 4 }}