{{- if .Values.api.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "notifications.fullname" . }}
  namespace: {{ include "notifications.namespace" . }}
  labels:
    {{- include "notifications.labels" (dict "context" . "name" .Values.api.name) | nindent 4 }}
  {{- with .Values.api.pdb.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if and (hasKey .Values.api.pdb "maxUnavailable") (ne .Values.api.pdb.maxUnavailable nil) }}
  maxUnavailable: {{ .Values.api.pdb.maxUnavailable }}
  {{- else }}
  minAvailable: {{ .Values.api.pdb.minAvailable | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "notifications.selectorLabels" (dict "context" . "name" .Values.api.name) | nindent 6 }}
{{- end }}
