apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reporter-helm.fullname" . }}-reporter-worker
  labels:
    {{- include "reporter-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: reporter-worker
type: Opaque
data:
  FETCHER_M2M_CLIENT_SECRET: {{ .Values.worker.secrets.FETCHER_M2M_CLIENT_SECRET | default "" | b64enc | quote }}
  # Extra Secret Vars
  {{- if .Values.worker.extraSecretVars }}
  {{- toYaml .Values.worker.extraSecretVars | nindent 2 }}
  {{- end }}
