{{- if $.Values.spb.enabled -}}
{{ include "br-sfn.componentDeployment" (dict "root" $ "name" "spb" "comp" $.Values.spb "defaultPort" 3000 "livenessPath" "/health" "readyPath" "/readyz") }}
{{- end -}}
