{{- if and .Values.tracer.enabled .Values.tracer.autoscaling.enabled }}
{{- include "lerian-common.hpa" (dict
      "autoscaling" .Values.tracer.autoscaling
      "name" (include "tracer.fullname" .)
      "namespace" (include "global.namespace" .)
      "labels" (include "tracer.labels" (dict "context" . "component" .Values.tracer.name "name" .Values.tracer.name))
    ) }}
{{- end }}
