{{- if and .Values.tracer.enabled .Values.tracer.ingress.enabled -}}
{{- include "lerian-common.ingress" (dict
      "context" .
      "ingress" .Values.tracer.ingress
      "name" (include "tracer.fullname" .)
      "namespace" (include "global.namespace" .)
      "labels" (include "tracer.labels" (dict "context" . "component" .Values.tracer.name "name" .Values.tracer.name))
      "svcPort" .Values.tracer.service.port
    ) }}
{{- end }}
