{{- if and .Values.tracer.enabled (not .Values.tracer.useExistingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tracer.fullname" . }}
  namespace: {{ include "global.namespace" . }}
  labels:
    {{- include "tracer.labels" (dict "context" . "component" .Values.tracer.name "name" .Values.tracer.name) | nindent 4 }}
type: Opaque
data:
  # PostgreSQL Secrets
  DB_PASSWORD: {{ .Values.tracer.secrets.DB_PASSWORD | default "lerian" | b64enc | quote }}

  # API Key Secrets
  API_KEY_SECRET: {{ .Values.tracer.secrets.API_KEY_SECRET | default "" | b64enc | quote }}
{{- end }}
