{{- if .Values.tracer.enabled }}
{{- include "lerian-common.service" (dict
      "service" .Values.tracer.service
      "name" (include "tracer.fullname" .)
      "namespace" (include "global.namespace" .)
      "labels" (include "tracer.labels" (dict "context" . "component" .Values.tracer.name "name" .Values.tracer.name))
      "selector" (include "tracer.selectorLabels" (dict "context" . "name" .Values.tracer.name))
    ) }}
{{- end }}
