{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "midaz-console.fullname" . }}-nginx
  namespace: {{ include "global.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "midaz-console.fullname" . }}-nginx
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: console-nginx
spec:
  type: {{ .Values.nginx.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "midaz-console.fullname" . }}-nginx
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.nginx.service.ports.http }}
      targetPort: http
{{- end }}
