{{- define "nginx.serverBlockConfig" -}}
  server {
    listen 8080;

    location / {
      proxy_pass http://midaz-console.midaz.svc.cluster.local:{{ get (get .Values.console "service" | default dict) "port" | default 8081 }};

      proxy_buffers 8 256k;
      proxy_buffer_size 256k;
      proxy_busy_buffers_size 256k;
      client-header-buffer-size 256k;
      large-client-header-buffers 4 256k;
    }

    include /opt/bitnami/nginx/conf/plugins_blocks/plugins.conf;
  }
{{- end }}

{{- define "nginx.pluginServerBlock" -}}
  location = /{{ .name }} {
    return 301 /{{ .name }}/;
  }
  location /{{ .name }}/ {
    proxy_pass http://{{ .name }}.midaz-plugins.svc.cluster.local:{{ .port }};
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_read_timeout 600s;
    proxy_connect_timeout 60s;
  }
{{- end }}


atualização dos templates dos helm para fechamento do ciclo
testes dos micro frontends no k8s (aguardando release de fix em dev do console)
documentação de guia de upgrade dos helm charts (plugin-crm, plugin-fees, plugin-smart-templates)


done:
Helm release das correções das UIs dos plugins
Teste das UIs dos plugins
Suporte de external secrets para todos os helm charts
Atualização/Revisão de todos os helms charts para o fechamento do ciclo com base nas releases das apps na develop
Documentação de guia de upgrade de todos os helms para a nova versão no fechamento do ciclo
