{{- if .Values.console.enabled }}
{{- if .Values.console.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "midaz-console.fullname" . }}
  labels:
    {{- include "midaz.labels" (dict "context" . "component" .Values.console.name "name" .Values.console.name ) | nindent 4 }}
  {{- with .Values.console.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}