{{- $component := index .Values "bc-correios" -}}
{{- if and $component.enabled $component.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bc-correios.serviceAccountName" . }}
  namespace: {{ include "global.namespace" . }}
  labels:
    {{- include "bc-correios.labels" (dict "context" . "component" $component.name "name" $component.name) | nindent 4 }}
  {{- with $component.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
