{{- if .Values.api.enabled }}
{{- include "lerian-common.service" (dict
      "service" (fromYaml (include "plugin-br-pix-jd.withCommonAnnotations" (dict "root" $ "block" .Values.api.service)))
      "name" (include "plugin-br-pix-jd.componentFullname" (dict "root" $ "name" "api"))
      "namespace" (include "plugin-br-pix-jd.namespace" $)
      "labels" (include "plugin-br-pix-jd.componentLabels" (dict "root" $ "name" "api"))
      "selector" (include "plugin-br-pix-jd.componentSelectorLabels" (dict "root" $ "name" "api"))) }}
{{- end }}
