{{- if .Values.configmap }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "midaz-ledger.fullname" . }}
type: Opaque
data:
  {{- with .Values.secrets }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}