apiVersion: v1
kind: Secret
metadata:
  name: {{ include "midaz-ledger.fullname" . }}
type: Opaque
data:
  MONGO_PASSWORD: {{ .Values.configmap.MONGO_PASSWORD | default "lerian" | b64enc | quote }}
  DB_PASSWORD: {{ .Values.configmap.DB_PASSWORD | default "lerian" | b64enc | quote }}
  DB_REPLICA_PASSWORD: {{ .Values.configmap.DB_REPLICA_PASSWORD | default "lerian" | b64enc | quote }}
  REPLICATION_PASSWORD: {{ .Values.configmap.REPLICATION_PASSWORD | default "lerian" | b64enc | quote }}