{{- $gIng := (.Values.global | default dict).ingress | default dict -}}
{{- if and .Values.crm.enabled (or .Values.crm.ingress.enabled $gIng.enabled) -}}
{{- include "lerian-common.ingress" (dict
      "context" .
      "ingress" .Values.crm.ingress
      "global" $gIng
      "subdomain" "crm"
      "name" (include "midaz-crm.fullname" .)
      "labels" (include "midaz-crm.labels" (dict "context" . "name" .Values.crm.name))
      "svcPort" .Values.crm.service.port
    ) }}
{{- end }}
