apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plugin-br-pix-switch.fullname" . }}
  labels:
    {{- include "plugin-br-pix-switch.labels" (dict "context" . "name" .Values.pixSwitch.name ) | nindent 4 }}
spec:
  revisionHistoryLimit: {{ .Values.pixSwitch.revisionHistoryLimit | default 10 }}
  strategy:
    {{- toYaml .Values.pixSwitch.deploymentStrategy | nindent 4 }}
  replicas: {{ .Values.pixSwitch.replicaCount }}
  selector:
    matchLabels:
      {{- include "plugin-br-pix-switch.selectorLabels" (dict "context" . "name" .Values.pixSwitch.name) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "plugin-br-pix-switch.labels" (dict "context" . "name" .Values.pixSwitch.name ) | nindent 8 }}
    spec:
    {{- with .Values.pixSwitch.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.pixSwitch.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "plugin-br-pix-switch.fullname" . }}
          securityContext:
            {{- toYaml .Values.pixSwitch.securityContext | nindent 12 }}
          image: {{ .Values.pixSwitch.image.repository }}:{{ .Values.pixSwitch.image.tag | default (include "plugin.version" .) }}
          imagePullPolicy: {{ .Values.pixSwitch.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.pixSwitch.service.port }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.pixSwitch.service.grpcPort }}
              protocol: TCP
          envFrom:
          - secretRef:
              name: {{ if .Values.pixSwitch.useExistingSecrets }}{{ .Values.pixSwitch.existingSecretName }}{{ else }}{{ include "plugin-br-pix-switch.fullname" . }}{{ end }}
          - configMapRef:
              name: {{ include "plugin-br-pix-switch.fullname" . }}
          {{ if (index .Values "otel-collector-lerian").enabled }}
          env:
          - name: "HOST_IP"
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: "OTEL_EXPORTER_OTLP_ENDPOINT"
            value: "$(HOST_IP):4317"
          {{ end }}
          resources:
            {{- toYaml .Values.pixSwitch.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: {{ .Values.pixSwitch.readinessProbe.path | default "/readyz" }}
              port: {{ .Values.pixSwitch.service.port }}
            initialDelaySeconds: {{ .Values.pixSwitch.readinessProbe.initialDelaySeconds | default 10 }}
            periodSeconds: {{ .Values.pixSwitch.readinessProbe.periodSeconds | default 5 }}
            timeoutSeconds: {{ .Values.pixSwitch.readinessProbe.timeoutSeconds | default 1 }}
            successThreshold: {{ .Values.pixSwitch.readinessProbe.successThreshold | default 1 }}
            failureThreshold: {{ .Values.pixSwitch.readinessProbe.failureThreshold | default 3 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.pixSwitch.livenessProbe.path | default "/live" }}
              port: {{ .Values.pixSwitch.service.port }}
            initialDelaySeconds: {{ .Values.pixSwitch.livenessProbe.initialDelaySeconds | default 5 }}
            periodSeconds: {{ .Values.pixSwitch.livenessProbe.periodSeconds | default 5 }}
            timeoutSeconds: {{ .Values.pixSwitch.livenessProbe.timeoutSeconds | default 1 }}
            successThreshold: {{ .Values.pixSwitch.livenessProbe.successThreshold | default 1 }}
            failureThreshold: {{ .Values.pixSwitch.livenessProbe.failureThreshold | default 3 }}
      {{- with .Values.pixSwitch.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pixSwitch.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pixSwitch.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
