{{- if .Values.pixSwitch.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "plugin-br-pix-switch.fullname" . }}
  labels:
    {{- include "plugin-br-pix-switch.labels" (dict "context" . "name" .Values.pixSwitch.name ) | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "plugin-br-pix-switch.fullname" . }}
  minReplicas: {{ .Values.pixSwitch.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.pixSwitch.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.pixSwitch.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.pixSwitch.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.pixSwitch.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.pixSwitch.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
