apiVersion: v1
kind: Service
metadata:
  name: {{ include "plugin-fees.fullname" . }}
  labels:
    {{- include "plugin-fees.labels" (dict "context" . "name" .Values.name ) | nindent 4 }} 
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "plugin-fees.selectorLabels" (dict "context" . "name" .Values.name) | nindent 4 }}