{{- if .Values.dictSystemplane.enabled }}
{{- $component := "dict-systemplane" }}
{{- $values := .Values.dictSystemplane }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "plugin-br-pix-switch.componentFullname" (dict "context" $ "component" $component) }}
  namespace: {{ include "global.namespace" . }}
  labels:
    {{- include "plugin-br-pix-switch.labels" (dict "context" $ "component" $component) | nindent 4 }}
  {{- with $values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $values.service.type }}
  ports:
    - port: {{ $values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "plugin-br-pix-switch.selectorLabels" (dict "context" $ "component" $component) | nindent 4 }}
{{- end }}
