apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reporter-helm.fullname" . }}-reporter-manager
  labels:
    {{- include "reporter-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: reporter-manager
type: Opaque
data:
  APP_ENC_KEY: {{ .Values.manager.secrets.APP_ENC_KEY | default "" | b64enc | quote }}
  # Extra Secret Vars
  {{- if .Values.manager.extraSecretVars }}
  {{- toYaml .Values.manager.extraSecretVars | nindent 2 }}
  {{- end }}
