apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plugin-auth.fullname" . }}
  labels:
    {{- include "plugin-auth.labels" (dict "context" . "name" .Values.auth.name ) | nindent 4 }} 
spec:
  revisionHistoryLimit: {{ .Values.auth.revisionHistoryLimit | default 10 }}
  strategy:
    {{- toYaml .Values.auth.deploymentStrategy | nindent 4 }}
  replicas: {{ .Values.auth.replicaCount }}
  selector:
    matchLabels:
      {{- include "plugin-auth.selectorLabels" (dict "context" . "name" .Values.auth.name) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "plugin-auth.labels" (dict "context" . "name" .Values.auth.name ) | nindent 8 }}
    spec:
    {{- with .Values.auth.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.auth.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-for-dependencies
          image: busybox
          envFrom:
          - configMapRef:
              name: {{ include "plugin-auth.fullname" . }}
          command:
            - /bin/sh
            - -c
            - |
              #!/bin/bash
              until wget --spider -q "$AUTHORIZER_ADDRESS/api/health"; do
                echo "Wait for backend...";
                sleep 5;
              done;
              echo "Backend is up!";
      containers:
        - name: {{ include "plugin-auth.fullname" . }}
          image: {{ .Values.auth.image.repository }}:{{ .Values.auth.image.tag | default (include "plugin.version" .) }}
          imagePullPolicy: {{ .Values.auth.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.auth.service.port }}
              protocol: TCP
          envFrom:
          - secretRef:
              name: {{ if .Values.auth.useExistingSecret }}{{ .Values.auth.existingSecretName }}{{ else }}{{ include "plugin-auth.fullname" . }}{{ end }}
          - configMapRef:
              name: {{ include "plugin-auth.fullname" . }}
          {{ if (index .Values "otel-collector-lerian").enabled }}
          env:
          - name: "HOST_IP"
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: "OTEL_EXPORTER_OTLP_ENDPOINT"
            value: "$(HOST_IP):4317"
          {{ end }}              
          resources:
            {{- toYaml .Values.auth.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: {{ .Values.auth.readinessProbe.path | default "/readyz" }}
              port: {{ .Values.auth.service.port }}
            initialDelaySeconds: {{ .Values.auth.readinessProbe.initialDelaySeconds | default 25 }}
            periodSeconds: {{ .Values.auth.readinessProbe.periodSeconds | default 5 }}
            {{- if and .Values.auth.readinessProbe (hasKey (.Values.auth.readinessProbe | default dict) "timeoutSeconds") }}
            timeoutSeconds: {{ .Values.auth.readinessProbe.timeoutSeconds }}
            {{- end }}
            {{- if and .Values.auth.readinessProbe (hasKey (.Values.auth.readinessProbe | default dict) "successThreshold") }}
            successThreshold: {{ .Values.auth.readinessProbe.successThreshold }}
            {{- end }}
            {{- if and .Values.auth.readinessProbe (hasKey (.Values.auth.readinessProbe | default dict) "failureThreshold") }}
            failureThreshold: {{ .Values.auth.readinessProbe.failureThreshold }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.auth.livenessProbe.path | default "/health" }}
              port: {{ .Values.auth.service.port }}
            initialDelaySeconds: {{ .Values.auth.livenessProbe.initialDelaySeconds | default 30 }}
            periodSeconds: {{ .Values.auth.livenessProbe.periodSeconds | default 5 }}
            {{- if and .Values.auth.livenessProbe (hasKey (.Values.auth.livenessProbe | default dict) "timeoutSeconds") }}
            timeoutSeconds: {{ .Values.auth.livenessProbe.timeoutSeconds }}
            {{- end }}
            {{- if and .Values.auth.livenessProbe (hasKey (.Values.auth.livenessProbe | default dict) "successThreshold") }}
            successThreshold: {{ .Values.auth.livenessProbe.successThreshold }}
            {{- end }}
            {{- if and .Values.auth.livenessProbe (hasKey (.Values.auth.livenessProbe | default dict) "failureThreshold") }}
            failureThreshold: {{ .Values.auth.livenessProbe.failureThreshold }}
            {{- end }}
      volumes:
        - name: backend-init-data
          configMap:
            name: {{ include "plugin-auth.fullname" . }}-init-data
            items:
              - key: init_data.json
                path: init_data.json       
      {{- with .Values.auth.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.auth.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.auth.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}