{{- if not .Values.auth.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "plugin-auth.fullname" . }}
  labels:
    {{- include "plugin-auth.labels" (dict "context" . "name" .Values.auth.name ) | nindent 4 }}
type: Opaque
data:
  # -- Default sensitive variables for the auth
  AUTHORIZER_CLIENT_SECRET: {{ required "auth.secrets.AUTHORIZER_CLIENT_SECRET is required" .Values.auth.secrets.AUTHORIZER_CLIENT_SECRET | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.auth.secrets.REDIS_PASSWORD | default "" | b64enc | quote }}
  DB_PASSWORD: {{ required "auth.secrets.DB_PASSWORD is required" .Values.auth.secrets.DB_PASSWORD | b64enc | quote }}
  LICENSE_KEY: {{ .Values.auth.secrets.LICENSE_KEY | b64enc | quote }}
  ORGANIZATION_IDS: {{ .Values.auth.secrets.ORGANIZATION_IDS | b64enc | quote }}
{{- end }}
