name: Helm Upgrade Doc

on:
  push:
    tags:
      - '**-v[0-9]*'

permissions:
  contents: write
  pull-requests: write

jobs:
  upgrade-doc:
    uses: LerianStudio/github-actions-shared-workflows/.github/workflows/helm-upgrade-doc.yml@feat/helm-upgrade-doc
    secrets: inherit
