{{- if and .Values.cobSystemplane.enabled .Values.cobSystemplane.serviceAccount.create }}
{{- $component := "cob-systemplane" }}
{{- $values := .Values.cobSystemplane }}
{{- include "lerian-common.serviceAccount" (dict
      "serviceAccount" $values.serviceAccount
      "name" (include "plugin-br-pix-lerian.componentServiceAccountName" (dict "context" $ "component" $component "componentValues" $values))
      "namespace" (include "global.namespace" $)
      "labels" (include "plugin-br-pix-lerian.labels" (dict "context" $ "component" $component))) }}
{{- end }}
